### ISSUE TITLE
Usunąć logikę z testów!

### ISSUE THREAD

**Issue by mles2** [Simon2833/PO_PWR#14]
https://github.com/Simon2833/PO_PWR/blob/8f09cc22f5457cd0ff06e6f53e3264bc917cda1f/unit_tests/test_board.py#L69

Testy powinny zawierać w sobie **jak najmniej logiki** - wynika to z prostego faktu, żeby dodać logikę do testów w sensowny sposób należałoby napisać testy na testy. W testowaniu proszę się skupić raczej na konkretnych prostych przykładach i warunkach brzegowych. Najlepsze testy to takie, które nie mają **ani jednej pętli i ani jednego ifa**.

Jako przykład, polecam stosować przy testach GIVEN/WHEN/THEN,
GIVEN - jakaś jednostka jest w konkretnym miejscu A (1,3) , druga jest w miejscu B(2,3)
WHEN - kiedy zostanie wywołane rangeBetween(A,B)
THEN -  rangeBetween zwróci 1

I tak dla każdego wymyślnego przypadku (niepoprawnych danych, odległości na ukos, itp itd).

**Comment by Simon2833** [comment]
Dziękujemy, po kolosach zabierzemy się za poprawę testów. 😄
